#%RAML 1.0
title: My API with Types
mediaType: application/json
types:
  Org:
    type: object
    properties:
      onCall: AlertableAdmin
      Head: Manager

  RelationHuman:
    type: boolean

  AgeHuman:
    type : integer
    minimum: 18
    maximum: 80
    format: int8

  AgeBuilding:
    type : integer
    minimum: 0
    maximum: 20000
    format: int16

  AgeFossil:
    type : integer
    minimum: 0
    maximum: 1000000
    format: int32

  AgeExistence:
    type : integer
    minimum: 0
    maximum: 1000000000
    format: int64

  FuzzyFloat:
    type: number
    format: float
    minimum: 0.00
    maximum: 1.00

  Fuzziness:
    type: number
    format: double
    minimum: 0.0001
    maximum: 1.000


  BirthDay:
    type : date-only

  LunchTime:
    type: time-only

  BirthDateTime:
    type: datetime-only


  Person:
    type: object
    properties:
      firstname: string
      lastname: string
      title?: string
  Phone:
    type: string
    pattern: "(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}"
  Manager:
    type: Person
    properties:
      reports: Person[]
      phone:
  Admin:
    type: Person
    properties:
      clearanceLevel:
        enum: [ low, high ]
  AlertableAdmin:
      type: Admin
      properties:
        phone: Phone
  Alertable: Manager | AlertableAdmin

/orgs/{orgId}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Org
